#!/bin/bash

if [ -z "$JAVA_HOME" -a -z "$JRE_HOME" ]; then
    echo "Neither the JAVA_HOME nor the JRE_HOME environment variable is defined"
    echo "At least one of these environment variable is needed to run this program"
    exit 1
fi

if [ -z "$JRE_HOME" ]; then
  JRE_HOME="$JAVA_HOME"
fi

if [ -z "$JSENDEMAIL_HOME" ]; then
  echo "the JSENDEMAIL_HOME environment variable should be defined"
  exit 1
fi


RUNJAVA="$JRE_HOME"/bin/java

CLASSWORLDS_LAUNCHER=org.codehaus.classworlds.Launcher

exec "$RUNJAVA" -classpath "${JSENDEMAIL_HOME}"/boot/*.jar "-Dclassworlds.conf=${JSENDEMAIL_HOME}/bin/jsendemail.conf" "-Djsendemail.home=${JSENDEMAIL_HOME}" ${CLASSWORLDS_LAUNCHER} "$@"